# Generated by Django 5.1.2 on 2025-06-01 17:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user", models.CharField(max_length=100)),
                ("voice_input", models.TextField()),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("call", "Call"),
                            ("email", "Email"),
                            ("meeting", "Meeting"),
                            ("reminder", "Reminder"),
                            ("document", "Documentation"),
                            ("followup", "Follow-up"),
                            ("offer", "Offer"),
                            ("general", "General Task"),
                        ],
                        default="general",
                        max_length=20,
                    ),
                ),
                ("action", models.CharField(max_length=100)),
                ("person", models.CharField(blank=True, max_length=100)),
                ("topic", models.CharField(blank=True, max_length=255)),
                ("deadline", models.CharField(blank=True, max_length=100)),
                (
                    "language",
                    models.CharField(
                        choices=[("en", "English"), ("de", "German")],
                        default="en",
                        max_length=2,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "workflow_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("workflow_status", models.CharField(default="pending", max_length=50)),
                ("assigned_to", models.CharField(blank=True, max_length=100)),
                ("priority", models.CharField(default="medium", max_length=20)),
                (
                    "calendar_event_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("calendar_event_link", models.URLField(blank=True, null=True)),
            ],
        ),
    ]
