# Generated by Django 5.2.1 on 2025-05-15 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="topic",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
